create table if not exists public.retro_tickets (
  id bigint generated by default as identity primary key,
  session_id text not null default 'demo',
  text text not null,
  author text not null,
  color text not null,
  x double precision not null default 42,
  y double precision not null default 44,
  is_private boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.retro_sessions (
  id text primary key,
  zones jsonb not null default '[]'::jsonb,
  is_open boolean not null default false,
  vote_finished boolean not null default false,
  ticket_zones jsonb not null default '{}'::jsonb,
  ticket_actions jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.retro_sessions
  add column if not exists ticket_actions jsonb not null default '{}'::jsonb;

create table if not exists public.retro_votes (
  id bigint generated by default as identity primary key,
  session_id text not null default 'demo',
  ticket_id bigint not null references public.retro_tickets(id) on delete cascade,
  author text not null,
  created_at timestamptz not null default now(),
  unique (session_id, ticket_id, author)
);

alter table public.retro_votes enable row level security;

create policy "Anyone can read retro votes"
  on public.retro_votes for select
  to anon, authenticated
  using (true);

create policy "Anyone can create retro votes"
  on public.retro_votes for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can remove own retro votes"
  on public.retro_votes for delete
  to anon, authenticated
  using (true);

alter table public.retro_sessions enable row level security;

create policy "Anyone can read retro session configuration"
  on public.retro_sessions for select
  to anon, authenticated
  using (true);

create policy "Anyone can configure retro session"
  on public.retro_sessions for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can update retro session"
  on public.retro_sessions for update
  to anon, authenticated
  using (true)
  with check (true);

alter table public.retro_tickets enable row level security;

create policy "Anyone can read retro tickets"
  on public.retro_tickets for select
  to anon, authenticated
  using (true);

create policy "Anyone can create retro tickets"
  on public.retro_tickets for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can move retro tickets"
  on public.retro_tickets for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Anyone can reset retro tickets"
  on public.retro_tickets for delete
  to anon, authenticated
  using (true);

alter publication supabase_realtime add table public.retro_tickets;
alter publication supabase_realtime add table public.retro_sessions;
alter publication supabase_realtime add table public.retro_votes;
