begin;

create table if not exists public.retro_tickets (
  id bigint generated by default as identity primary key,
  session_id text not null,
  text text not null,
  author text not null,
  color text not null,
  x double precision not null default 42,
  y double precision not null default 44,
  is_private boolean not null default true,
  in_report boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.retro_sessions (
  id text primary key,
  zones jsonb not null default '[]'::jsonb,
  is_open boolean not null default false,
  vote_open boolean not null default false,
  vote_finished boolean not null default false,
  ticket_zones jsonb not null default '{}'::jsonb,
  ticket_actions jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.retro_sessions
  add column if not exists zones jsonb not null default '[]'::jsonb,
  add column if not exists is_open boolean not null default false,
  add column if not exists vote_open boolean not null default false,
  add column if not exists vote_finished boolean not null default false,
  add column if not exists ticket_zones jsonb not null default '{}'::jsonb,
  add column if not exists ticket_actions jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.retro_votes (
  id bigint generated by default as identity primary key,
  session_id text not null,
  ticket_id bigint not null references public.retro_tickets(id) on delete cascade,
  author text not null,
  created_at timestamptz not null default now(),
  unique (session_id, ticket_id, author)
);

alter table public.retro_tickets
  add column if not exists session_id text,
  add column if not exists is_private boolean not null default true,
  add column if not exists in_report boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

alter table public.retro_votes
  add column if not exists session_id text,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'retro_tickets'
      and column_name = 'private'
  ) then
    execute 'update public.retro_tickets set is_private = coalesce("private", true)';
  end if;
end
$$;

update public.retro_tickets
set session_id = 'LEGACY0001'
where session_id is null or btrim(session_id) = '';

delete from public.retro_votes vote
where vote.ticket_id is null
   or vote.author is null
   or btrim(vote.author) = ''
   or not exists (
     select 1 from public.retro_tickets ticket where ticket.id = vote.ticket_id
   );

delete from public.retro_votes vote
using public.retro_votes duplicate
where vote.id > duplicate.id
  and vote.ticket_id = duplicate.ticket_id
  and vote.author = duplicate.author;

update public.retro_votes vote
set session_id = ticket.session_id
from public.retro_tickets ticket
where ticket.id = vote.ticket_id
  and vote.session_id is distinct from ticket.session_id;

insert into public.retro_sessions (id)
select distinct ticket.session_id
from public.retro_tickets ticket
where not exists (
  select 1 from public.retro_sessions session where session.id = ticket.session_id
);

alter table public.retro_tickets alter column session_id set not null;
alter table public.retro_votes alter column session_id set not null;

alter table public.retro_tickets alter column session_id drop default;
alter table public.retro_votes alter column session_id drop default;

delete from public.retro_votes vote
using public.retro_votes duplicate
where vote.id > duplicate.id
  and vote.session_id = duplicate.session_id
  and vote.ticket_id = duplicate.ticket_id
  and vote.author = duplicate.author;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'retro_tickets_id_session_key' and conrelid = 'public.retro_tickets'::regclass) then
    alter table public.retro_tickets
      add constraint retro_tickets_id_session_key unique (id, session_id);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_tickets_session_fkey' and conrelid = 'public.retro_tickets'::regclass) then
    alter table public.retro_tickets
      add constraint retro_tickets_session_fkey
      foreign key (session_id) references public.retro_sessions(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_votes_ticket_session_fkey' and conrelid = 'public.retro_votes'::regclass) then
    alter table public.retro_votes
      add constraint retro_votes_ticket_session_fkey
      foreign key (ticket_id, session_id)
      references public.retro_tickets(id, session_id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_votes_session_ticket_author_key' and conrelid = 'public.retro_votes'::regclass) then
    alter table public.retro_votes
      add constraint retro_votes_session_ticket_author_key
      unique (session_id, ticket_id, author);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_sessions_vote_state_check' and conrelid = 'public.retro_sessions'::regclass) then
    alter table public.retro_sessions
      add constraint retro_sessions_vote_state_check
      check (not (vote_open and vote_finished)) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_tickets_text_check' and conrelid = 'public.retro_tickets'::regclass) then
    alter table public.retro_tickets
      add constraint retro_tickets_text_check
      check (char_length(btrim(text)) between 1 and 160) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_tickets_author_check' and conrelid = 'public.retro_tickets'::regclass) then
    alter table public.retro_tickets
      add constraint retro_tickets_author_check
      check (char_length(btrim(author)) between 1 and 24) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'retro_votes_author_check' and conrelid = 'public.retro_votes'::regclass) then
    alter table public.retro_votes
      add constraint retro_votes_author_check
      check (char_length(btrim(author)) between 1 and 24) not valid;
  end if;
end
$$;

create index if not exists retro_tickets_session_created_idx
  on public.retro_tickets (session_id, created_at);

create index if not exists retro_votes_session_created_idx
  on public.retro_votes (session_id, created_at);

create or replace function public.set_retro_session_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_retro_session_updated_at on public.retro_sessions;
create trigger set_retro_session_updated_at
before update on public.retro_sessions
for each row execute function public.set_retro_session_updated_at();

create or replace function public.enforce_retro_vote_limit()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.session_id || ':' || new.author, 0));
  if (
    select count(*)
    from public.retro_votes
    where session_id = new.session_id and author = new.author
  ) >= 3 then
    raise exception 'A participant cannot cast more than three votes per session'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_retro_vote_limit on public.retro_votes;
create trigger enforce_retro_vote_limit
before insert on public.retro_votes
for each row execute function public.enforce_retro_vote_limit();

alter table public.retro_votes enable row level security;

alter table public.retro_sessions enable row level security;
drop policy if exists "Anyone can read retro session configuration" on public.retro_sessions;
drop policy if exists "Anyone can configure retro session" on public.retro_sessions;
drop policy if exists "Anyone can update retro session" on public.retro_sessions;
drop policy if exists "Anyone can reset retro session" on public.retro_sessions;

create policy "Anyone can read retro session configuration"
  on public.retro_sessions for select
  to anon, authenticated
  using (true);

create policy "Anyone can configure retro session"
  on public.retro_sessions for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can update retro session"
  on public.retro_sessions for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Anyone can reset retro session"
  on public.retro_sessions for delete
  to anon, authenticated
  using (true);

alter table public.retro_tickets enable row level security;
drop policy if exists "Anyone can read retro tickets" on public.retro_tickets;
drop policy if exists "Anyone can create retro tickets" on public.retro_tickets;
drop policy if exists "Anyone can move retro tickets" on public.retro_tickets;
drop policy if exists "Anyone can reset retro tickets" on public.retro_tickets;
drop policy if exists "Anyone can read retro votes" on public.retro_votes;
drop policy if exists "Anyone can create retro votes" on public.retro_votes;
drop policy if exists "Anyone can remove own retro votes" on public.retro_votes;

create policy "Anyone can read retro tickets"
  on public.retro_tickets for select
  to anon, authenticated
  using (true);

create policy "Anyone can create retro tickets"
  on public.retro_tickets for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can move retro tickets"
  on public.retro_tickets for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "Anyone can reset retro tickets"
  on public.retro_tickets for delete
  to anon, authenticated
  using (true);

create policy "Anyone can read retro votes"
  on public.retro_votes for select
  to anon, authenticated
  using (true);

create policy "Anyone can create retro votes"
  on public.retro_votes for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can remove own retro votes"
  on public.retro_votes for delete
  to anon, authenticated
  using (true);

alter table public.retro_tickets replica identity full;
alter table public.retro_votes replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') and not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime' and c.oid = 'public.retro_tickets'::regclass
  ) then
    alter publication supabase_realtime add table public.retro_tickets;
  end if;

  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') and not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime' and c.oid = 'public.retro_sessions'::regclass
  ) then
    alter publication supabase_realtime add table public.retro_sessions;
  end if;

  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') and not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime' and c.oid = 'public.retro_votes'::regclass
  ) then
    alter publication supabase_realtime add table public.retro_votes;
  end if;
end
$$;

notify pgrst, 'reload schema';

commit;
